<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abb020a0a757365722e70726f746f12056d6f64656c22550a0455736572" .
            "120a0a026964180120012809120c0a046e616d6518022001280912100a08" .
            "70617373776f726418032001280912210a0667656e64657218042001280e" .
            "32112e6d6f64656c2e5573657247656e64657222250a08557365724c6973" .
            "7412190a046c69737418012003280b320b2e6d6f64656c2e557365722a31" .
            "0a0a5573657247656e646572120d0a09554e444546494e4544100012080a" .
            "044d414c451001120a0a0646454d414c451002326d0a0555736572731231" .
            "0a085265676973746572120b2e6d6f64656c2e557365721a162e676f6f67" .
            "6c652e70726f746f6275662e456d707479220012310a044c69737412162e" .
            "676f6f676c652e70726f746f6275662e456d7074791a0f2e6d6f64656c2e" .
            "557365724c6973742200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

