<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garage.proto

namespace Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.GarageCoordinate</code>
 */
class GarageCoordinate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     */
    private $latitude = 0.0;
    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     */
    private $longitude = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $latitude
     *     @type float $longitude
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Garage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * Generated from protobuf field <code>float latitude = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * Generated from protobuf field <code>float longitude = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkFloat($var);
        $this->longitude = $var;

        return $this;
    }

}

