<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garage.proto

namespace Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.GarageAndUserId</code>
 */
class GarageAndUserId extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     */
    private $user_id = '';
    /**
     * Generated from protobuf field <code>.model.Garage garage = 2;</code>
     */
    private $garage = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $user_id
     *     @type \Model\Garage $garage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Garage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * Generated from protobuf field <code>string user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->user_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.Garage garage = 2;</code>
     * @return \Model\Garage
     */
    public function getGarage()
    {
        return $this->garage;
    }

    /**
     * Generated from protobuf field <code>.model.Garage garage = 2;</code>
     * @param \Model\Garage $var
     * @return $this
     */
    public function setGarage($var)
    {
        GPBUtil::checkMessage($var, \Model\Garage::class);
        $this->garage = $var;

        return $this;
    }

}

