<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garage.proto

namespace Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.Garage</code>
 */
class Garage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    private $id = '';
    /**
     * Generated from protobuf field <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * Generated from protobuf field <code>.model.GarageCoordinate coordinate = 3;</code>
     */
    private $coordinate = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $name
     *     @type \Model\GarageCoordinate $coordinate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Garage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.model.GarageCoordinate coordinate = 3;</code>
     * @return \Model\GarageCoordinate
     */
    public function getCoordinate()
    {
        return $this->coordinate;
    }

    /**
     * Generated from protobuf field <code>.model.GarageCoordinate coordinate = 3;</code>
     * @param \Model\GarageCoordinate $var
     * @return $this
     */
    public function setCoordinate($var)
    {
        GPBUtil::checkMessage($var, \Model\GarageCoordinate::class);
        $this->coordinate = $var;

        return $this;
    }

}

