<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: garage.proto

namespace Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>model.GarageListByUser</code>
 */
class GarageListByUser extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .model.GarageList> list = 1;</code>
     */
    private $list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $list
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Garage::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .model.GarageList> list = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * Generated from protobuf field <code>map<string, .model.GarageList> list = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Model\GarageList::class);
        $this->list = $arr;

        return $this;
    }

}

